# Copy of .devcontainer/Dockerfile for root-level compose builds
ARG VARIANT=8-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/php:0-${VARIANT}

# 设置为中国国内源
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# Install MariaDB client, ImageMagick, FreeType
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y mariadb-client zlib1g-dev libpng-dev libzip-dev libwebp-dev libmagickwand-dev libfreetype6-dev libjpeg62-turbo-dev \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install php-imagick
RUN pecl install imagick \
    && docker-php-ext-enable imagick

# configure gd
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

# Install php-mysql driver
RUN docker-php-ext-install mysqli pdo pdo_mysql gd zip

ARG NODE_VERSION="none"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

RUN a2enmod rewrite

ENV QT_QPA_PLATFORM=offscreen
ENV MOZ_HEADLESS=1
ENV DISPLAY=

RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c ". /usr/local/share/nvm/nvm.sh && npm install -g yarn@1.22.22"; fi

COPY .devcontainer/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
